#!/usr/bin/env python

"""Label the a sequence of features using the phone loop model."""

import argparse
import pickle
import amdtk


def main(script_args=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--hmm_states', action='store_true',
                        help='output the hmm states as units')
    parser.add_argument('--lscale', default=0., type=float,
                        help='log scale for the units weights', metavar='LS')
    parser.add_argument('--lscale_full', default=0., type=float,
                        help='log scale for the all the transition weights',
                        metavar='LS')
    parser.add_argument('model', help='model to fit on the data')
    parser.add_argument('feats', help='features of the utterance')
    parser.add_argument('out', help='labels in a HTK label file')
    args = parser.parse_args(script_args)

    # Load the unit-loop model.
    with open(args.model, 'rb') as f:
        model = pickle.load(f)

    # Load the features.
    X, infos = amdtk.readHtk(args.feats, infos=True)

    # Decode the utterance with the unit-loop model.
    path = amdtk.phoneLoopDecode(model, X, output_states=args.hmm_states)

    # Convert the best-path to HTK label data structure.
    mlf_data = []
    previous_state = path[0]
    start = 0
    for i, state in enumerate(path[1:]):
        if state != previous_state:
            mlf_data.append((previous_state, start, i+1, None, None))
            previous_state = state
            start = i+1
    mlf_data.append((previous_state, start, i+2, None, None))

    # Write the best-path alignment as a HTK label file.
    amdtk.writeHtkLabels(args.out, mlf_data, infos[1])

if __name__ == '__main__':
    main()
