#!/usr/bin/env python

"""Update the hyper-parameters of the posterior distribution of the
Bayesian phone loop model.
"""

import argparse
import pickle
import amdtk


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('model', type=argparse.FileType('rb'),
                        help='model to maximize')
    parser.add_argument('stats', type=argparse.FileType('rb'),
                        help='list of statistics files for the current model')
    parser.add_argument('output', type=argparse.FileType('wb'),
                        help='the updated model')
    args = parser.parse_args()

    # load the model.
    model = pickle.load(args.model)

    # Load the sufficient statistics.
    E_log_p_X, stats = pickle.load(args.stats)

    # VB-maximization step.
    amdtk.phoneLoopVbMaximization(model, stats)

    # Print the lower bound of log-likelihood.
    print(E_log_p_X - model.KLPosteriorPrior())
    #print('E[log p(X)] =', E_log_p_X, 'KL =', model.KLPosteriorPrior())

    # Dump the updated model on the disk.
    pickle.dump(model, args.output)

if __name__ == '__main__':
    main()
else:
    raise ImportError('this script cannot be imported')
