#!/usr/bin/env python

"""Create a model."""

import argparse
import pickle
import amdtk


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--seed', default=-1, type=int, help='value to seed '
                        'the random generators with')
    parser.add_argument('stats', help='stats of the features')
    parser.add_argument('config', help='model configuration file')
    parser.add_argument('output', help='the created model')
    args = parser.parse_args()

    # Seed the random generators if requested.
    if args.seed > 0:
        import numpy
        import random
        numpy.random.seed(args.seed)
        random.seed(args.seed)

    # Load the stats of the data for initializing the Gaussians.
    with open(args.stats, 'rb') as f:
        stats = pickle.load(f)

    # Create the model
    model = amdtk.models.Model.create(args.config, stats)

    # Dump the model on the disk.
    with open(args.output, 'wb') as f:
        pickle.dump(model, f)

if __name__ == '__main__':
    main()
else:
    raise ImportError('this script cannot be imported')
