#!/usr/bin/env python

"""Compute the unit alignment posteriors from the Forward-Backward
algorithm."""

import argparse
import pickle
import amdtk


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ac_weight', type=float, default=1.0,
                        help='scaling of the acoustic score')
    parser.add_argument('--hmm_states', action='store_true',
                        help='output the hmm states posteriors')
    parser.add_argument('model', help='model to fit on the data')
    parser.add_argument('feats', help='features of the utterance')
    parser.add_argument('out', help='HTK binary file')
    args = parser.parse_args()

    # Load the unit-loop model.
    with open(args.model, 'rb') as f:
        model = pickle.load(f)

    # Load the features.
    X, infos = amdtk.readHtk(args.feats, infos=True)

    # Compute the forward-backward per-frame posteriors.
    p = amdtk.phoneLoopForwardBackwardPosteriors(model, X, 
                                                 ac_weight=args.ac_weight,
                                                 output_states=args.hmm_states)

    # Dump the posteriors on the disk.
    amdtk.writeHtk(args.out, p, infos[1])

if __name__ == '__main__':
    main()
else:
    raise ImportError('this script cannot be imported')
