#!/usr/bin/env python

"""Update the hyper-parameters of the posterior distribution of the
Bayesian phone loop model.
"""

import argparse
import pickle
import amdtk


def main(model, stats, output):
    model = pickle.load(model)
    E_log_p_X, stats = pickle.load(stats)
    amdtk.phoneLoopVbMaximization(model, stats)

    import numpy as np
    np.seterr(all='raise')

    # Print the lower bound of log-likelihood
    print(E_log_p_X - model.KLPosteriorPrior())

    pickle.dump(model, output)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('model', type=argparse.FileType('rb'),
                        help='model to maximize')
    parser.add_argument('stats', type=argparse.FileType('rb'),
                        help='list of statistics files for the current model')
    parser.add_argument('output', type=argparse.FileType('wb'),
                        help='the updated model')
    args = parser.parse_args()
    main(args.model, args.stats, args.output)
else:
    raise ImportError('this script cannot be imported')
