#!/usr/bin/env python

"""First step of the variational inference. It compute the expected
value of the latent variables and the subsequent sufficient statistics
of the model for the given data.
"""

import argparse
import pickle
import amdtk


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--new_feats', help='features files on which to '
                                            'accumulate the stats.')
    parser.add_argument('model', help='model to fit on the data')
    parser.add_argument('feats', help='features file')
    parser.add_argument('out', help='accumulated statistics')
    args = parser.parse_args()
    
    with open(args.model, 'rb') as f:
        model = pickle.load(f)
    X = amdtk.readHtk(args.feats)
    if args.new_feats is None:
        Y = amdtk.readHtk(args.feats)
    else:
        Y = None
    E_log_p_X, stats = amdtk.phoneLoopVbExpectation(model, X, Y)
    with open(args.out, 'wb') as f:
        pickle.dump((E_log_p_X, stats), f)

if __name__ == '__main__':
    main()
else:
    raise ImportError('this script cannot be imported')
