#!/usr/bin/env python

"""Estimate the statistics of the data set. Those statistics are needed
for the definition of the hyper-parameters of the Bayesian phone loop
model.
"""

import argparse
import numpy as np
import pickle
import amdtk


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('featlist', help='list of input features file')
    parser.add_argument('output', help='statistics of the data set')
    args = parser.parse_args()

    mean = None
    cov = None
    count = 0
    with open(args.featlist, 'r') as f:
        for line in f:
            path = line.strip()
            X = amdtk.readHtk(path)
            if mean is None:
                mean = np.zeros(X.shape[1])
                cov = np.zeros_like(mean)
            mean += X.sum(axis=0)
            cov += (X**2).sum(axis=0)
            count += X.shape[0]
    mean = mean/count
    cov = cov/count - mean**2
    stats = {'mean': mean, 'cov': cov}
    with open(args.output, 'wb') as f:
        pickle.dump(stats, f)

if __name__ == '__main__':
    main()
else:
    raise ImportError('this script cannot be imported')
