#!/usr/bin/env python

"""First step of the variational inference. It computes the expected
value of the latent variables and the subsequent sufficient statistics
of the model for the given data.
"""

import argparse
import pickle
import amdtk


def main(script_args=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ac_weight', type=float, default=1.0,
                        help='scaling of the acoustic score')
    parser.add_argument('--new_feats', help='features files on which to '
                                            'accumulate the stats.')
    parser.add_argument('model', help='model to fit on the data')
    parser.add_argument('feats', help='features file')
    parser.add_argument('out', help='accumulated statistics')
    args = parser.parse_args(script_args)

    # Load the unit-loop model.
    with open(args.model, 'rb') as f:
        model = pickle.load(f)

    # Load the features for the alignment.
    X = amdtk.readHtk(args.feats)

    # Eventually, load an alternative set of features for the
    # accumulation.
    if args.new_feats is not None:
        Y = amdtk.readHtk(args.new_feats)
    else:
        Y = None

    # VB expectation.
    E_log_p_X, stats = amdtk.phoneLoopVbExpectation(model, X, Y,
                                                    ac_weight=args.ac_weight)

    # Dump the statistics on the disk.
    with open(args.out, 'wb') as f:
        pickle.dump((E_log_p_X, stats), f)

if __name__ == '__main__':
    main()
