#!/usr/bin/env python
import argparse
import sys
import os
from amdtk import readCTM


class OffsetFromSegmentFile:
    def __init__(self, segments_file, file_transform):
        self.file_transform = file_transform
        with open(segments_file) as fp:
            self.segments_offset = dict()
            for line in fp:
                file, start, end = line.split()
                self.segments_offset[file] = float(start)
                
    def __call__(self, file):
        return self.segments_offset[self.file_transform(file)]


def safe_open(filename, sys_file, mode):
    if filename == '-':
        file_handle = sys_file
    else:
        try:
            file_handle = open(filename, mode)
        except OSError:
            sys.exit(filename + " file not found!")
    return file_handle


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('ctmfile', metavar='CTMFILE', type=str, default='-',
                        nargs='?',
                        help=('The ctm file to be converted. '
                              'default: stdin'))
    parser.add_argument('outfile', metavar='OUTFILE', type=str, default='-',
                        nargs='?',
                        help=('The output mlf file to be created. '
                              'default: stdout'))
    parser.add_argument('-s', '--segments_file',
                        help='Segments file with timing offset information')
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--zerospeech', action='store_true',
                       help='the file to convert is in zerospeech format')
    group.add_argument('--latticewordseg', action='store_true',
                       help='the file to convert is in LatticeWordSegmentation format')
    args = parser.parse_args()

    file_transform = lambda filename: os.path.splitext(filename)[0]

    offset = None
    if args.segments_file is not None:
        offset = OffsetFromSegmentFile(args.segments_file, file_transform)
        
    if args.zerospeech:
        pos = (0, 3, 1, 2)
    if args.latticewordseg:
        pos = (1, 2, 3, 4)

    with safe_open(args.ctmfile, sys.stdin, 'r') as ctmfile:
        ctm = readCTM(ctmfile, file_transform=file_transform,
                      blacklist=('</s>',), pos=pos,
                      offset_from_filename=offset)

    with safe_open(args.outfile, sys.stdout, 'w') as outfile:
        print('#!MLF!#', file=outfile)
        for file, transcript in ctm.items():
            print('"*/{}.lab"'.format(file), file=outfile)
            for key, start, end in transcript:
                print('{} {} {}'.format(int(start*10000000), int(end*10000000), key),
                      file=outfile)
            print('.', file=outfile)

if __name__ == '__main__':
    main()
